Update 1

diff --git a/1 b/1
--- a/1
+++ b/1
@@ -1,12 +1,7 @@
-UTPUT_DIR      = /tmp
-VALUES_TEMPLATE = values-template.yaml
-================================
-[INFO] Sending status to API: {"cluster_name":"Core-infra","status":"Tool Installation Started"}
-{"message":"status updated","cluster_name":"Core-infra","status":"Tool Installation Started","storage":"redis","processing_time_ms":1.23}Creating values template...
-Template written to /tmp/values-template.yaml
-Rendering values.yml...
-Created /tmp/values.yml
-Rendering event-exporter.yaml...
-Created /tmp/event-exporter.yaml
-Done rendering templates.
-Error: looks like "https://charts.bitnami.com/bitnami" is not a valid chart repository or cannot be reached: Get "https://charts.bitnami.com/bitnami/index.yaml": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
+if ! retry_helm helm upgrade --install event-exporter  oci://registry-1.docker.io/bitnamicharts/kubernetes-event-exporter -n "$NAMESPACE" -f "/tmp/values.yml" --set im>
+  STATUS_MSG="Installation Failed"
+  echo "[ERROR] event-exporter install failed after retries"
+  exit 1
+  # send_status here if you want
+fi
+
